---
title: HW 5
author: Haley Uyeunten
output: html_document
---

```{r}
library(tidyverse)
library(socviz)
library(nycflights13)
library(gapminder)
library(ggrepel)
```

# Activity 1
```{r}
p <- ggplot(data = gss_sm, mapping = aes(x = age, y = childs))
p + geom_point(alpha = 0.2) + facet_grid(sex ~ happy)
```

# Activity 2
```{r}
happiness <- gss_sm %>%
  group_by(bigregion, happy) %>%
  summarize(N = n()) %>%
  mutate(freq = N / sum(N),
         pct = round((freq * 100), 0))
p <- ggplot(data = happiness, aes(x = bigregion, y = pct, fill = happy))
p + geom_bar(position = "dodge2", stat = "identity")
```

No, all the levels of happiness are similar between the regions.

# Activity 3
```{r}
d <- weather %>%
    group_by(month) %>%
    summarize_if(is.numeric, list(median = median), na.rm = TRUE) %>%
    ungroup()
p <- ggplot(data = d,
    mapping = aes(x = wind_speed_median, y = factor(month)))
p + geom_point() + scale_y_discrete(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
    labels = c("January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"),
    limits = rev)
```

# Activity 4
```{r}
a <- gapminder %>% filter(continent == "Americas" & year == "2007")
p <- ggplot(data = a, mapping = aes(x = gdpPercap, y = pop))
p + geom_point() + scale_x_log10() + geom_label_repel(
    box.padding = 2,
    nudge_y = -1,
    aes(label = country),
    max.overlaps = Inf)
```

# Activity 5
```{r}
a <- gapminder %>% filter(continent == "Americas" & year == "2007")
p <- ggplot(data = a, mapping = aes(x = gdpPercap, y = pop))
p + geom_point() + scale_x_log10() + geom_label_repel(
      data = subset(a, gdpPercap > 30000),
      mapping = aes(label = country)
    ) + geom_label_repel(
      data = subset(a, lifeExp < 68),
      mapping = aes(label = country)
    ) + annotate(
      geom = "rect", xmin = 30000, xmax = 60000,
      ymin = 0, ymax = 310000000, fill = "blue", alpha = 0.2
    ) + annotate(
      geom = "text", x = 45000, y = 150000000,
      label = "High GDP"
    )
```

# Activity 6
