---
title: HW 6
author: Haley Uyeunten
output: html_document
---

```{r}
library(tidyverse)
library(gapminder)
library(RColorBrewer)
library(broom)
```

# Activity 1
```{r}
c <- gapminder %>% filter(country == "Canada")
p <- ggplot(data = c, mapping = aes(x = year, y = pop))
model_colors <- brewer.pal(3, "Dark2")
p1 <- p + geom_point() +
    geom_smooth(method = "lm", aes(color = "Linear", fill = "Linear")) +
    geom_smooth(method = "lm", formula = y ~ splines::bs(x, df = 3),
                aes(color = "Cubic Spline", fill = "Cubic Spline")) +
    geom_smooth(method = "loess", aes(color = "LOESS", fill = "LOESS"))

p1 + scale_color_manual(name = "Models", values = model_colors) +
    scale_fill_manual(name = "Models", values = model_colors) +
    theme(legend.position = "right")
```
 

# Activity 2
```{r}
a <- gapminder %>% filter(continent == "Americas")
reg <- lm(data = a, pop ~ year + country)
all <- mutate(a, pred = predict(reg, newdata = a, level = 0.95))
c <- all %>% filter(country == "Canada")
g1 <- ggplot(data = c, aes(x = year, y = pop))
g1 + geom_point()
p <- all %>% filter(country == "Peru")
g2 <- ggplot(data = p, aes(x = year, y = pop))
g2 + geom_point()
b0 <- reg$coefficients[1]
b1 <- reg$coefficients[2]
c_detrend <- mutate(c, fitted = b0 + b1 * year, diff = pop - fitted)
g3 <- ggplot(data = c_detrend, aes(x = diff, y = fitted))
g3 + geom_line()
p_detrend <- mutate(p, fitted = b0 + b1 * year, diff = pop - fitted)
g4 <- ggplot(data = p_detrend, aes(x = diff, y = fitted))
g4 + geom_line()
```

It shows that the linear model isn't reasonable, since there's so much inconsistent 
difference between the predicted values and the actual values.

# Activity 3
```{r}
fit_ols <- function(df) {
    lm(lifeExp ~ log(gdpPercap), data = df)
}

out_le <- gapminder %>%
    filter(continent == "Americas") %>%
    group_by(country, year) %>%
    nest() %>%
    mutate(model = map(data, fit_ols),
            tidied = map(model, tidy)) %>%
    unnest(tidied)

p <- ggplot(data = out_le,
            mapping = aes(x = year, y = estimate,
                          ymin = estimate - 2 * std.error,
                          ymax = estimate + 2 * std.error,
                          group = country, color = country))

p + geom_pointrange(position = position_dodge(width = 1)) +
    scale_x_continuous(breaks = unique(gapminder$year)) +
    theme(legend.position = "top") +
    labs(x = "Year", y = "Estimate", color = "Country")
```

The populations of each country all increase as years increase.